import pathlib
out = pathlib.Path("D:/ailocal/acm-ai/docs/sprint-artifacts/e2e-evidence/observability-findings.md")
L = []
def a(x=""): L.append(x)
a("# Observability Findings: SSE Events + Pipeline Changes")
a()
a("**Date:** 2026-03-20")
a("**Investigator:** acm-observability-debugger")
a("**Scope:** New SSE events, grouped save, full pipeline event flow, cross-layer consistency.")
a()
a("---")
a()
a("## 1. SSE Event Bus -- New Events")
a()
a("### 1a. extraction.docling_complete")
a()
a("**Status:** DEFINED but WILL FAIL at runtime due to invalid SurrealQL query.")
a()
a("**BUG FOUND -- Invalid SurrealQL query (Severity: HIGH)**")
a()
a("The query at acm_commands.py:267 references a non-existent column page_numbers.")
a("The acm_table_section schema (migration 18.surrealql) only defines page_start (int) and page_end (int).")
a("No page_numbers array column exists. The query fails silently (caught by except Exception at line 292).")
a("The extraction.docling_complete event will NEVER be emitted in practice.")
a()
a("### 1b. ai.building_saved")
a()
a("**Status:** PROPERLY DEFINED and CORRECTLY WIRED. No issues found.")
a()
a("### 1c. Enriched AIBuildingExtractedData")
a()
a("**Status:** PROPERLY DEFINED with optional metadata fields. No issues found.")
a()
a("---")
a()
a("## 2. Grouped Save in save_records()")
a()
a("**Status:** CORRECTLY IMPLEMENTED.")
a()
a("- Sort key matches groupby key. itertools.groupby works correctly.")
a("- building_id=None is safely coalesced to the string unknown.")
a("- Per-building ai.building_saved emitted after each group saves. Correct.")
a("- Existing ai.save_progress events (every 10 records) preserved. No interference.")
a("- No race condition: save_records() is single-threaded LangGraph node.")
a()
a("---")
a()
a("## 3. Pipeline Event Flow Trace")
a()
a("| Step | Event | Status |")
a("|------|-------|--------|")
a("| 1. Upload | sets review_status=extracting | OK |")
a("| 4. extraction.started | acm_commands.py:217 | OK |")
a("| 5. extraction.docling_complete | acm_commands.py:258 | WILL FAIL (bad query) |")
a("| 6. ai.building_extracted | acm_extraction.py:810 | OK |")
a("| 7. ai.save_started | acm_extraction.py:2772 | OK |")
a("| 8. ai.save_progress | acm_extraction.py:2861 | OK |")
a("| 9. ai.building_saved | acm_extraction.py:2885 | OK |")
a("| 10. ai.save_complete | acm_extraction.py:2954 | OK |")
a("| 11. extraction.complete | acm_extraction.py:3403 | OK |")
a("| 12. review_status=pending_review | acm_commands.py:537 | OK |")
a()
a("---")
a()
a("## 4. Frontend Terminal Event Consistency")
a()
a("**BUG FOUND -- Terminal event set mismatch (Severity: MEDIUM)**")
a()
a("Backend v3_streaming.py terminal events include extraction.complete and extraction.failed.")
a("Frontend useV3SSE.ts TERMINAL_EVENT_TYPES is MISSING both of these.")
a("This causes unnecessary SSE reconnect attempts after backend closes the stream.")
a()
a("ExtractionLiveView.tsx and extract/page.tsx have the same gap.")
a()
a("extraction.docling_complete and ai.building_saved have no dedicated frontend rendering.")
a("They fall through to generic label rendering. Acceptable for now.")
a()
a("---")
a()
a("## 5. Database State")
a()
a("- review_status transitions are covered for all terminal paths.")
a("- extraction_progress terminal status written by UPSERT. Handles edge cases.")
a()
a("---")
a()
a("## 6. Observability Stack Status")
a()
a("| Component | Status |")
a("|-----------|--------|")
a("| Langfuse (localhost:3000) | DOWN |")
a("| LangGraph API (127.0.0.1:2024) | DOWN |")
a("| API (localhost:5055) | UP |")
a("| Logfire | DISABLED |")
a()
a("---")
a()
a("## 7. Summary")
a()
a("### Bugs")
a()
a("| # | Severity | Component | Description |")
a("|---|----------|-----------|-------------|")
a("| 1 | HIGH | acm_commands.py:267 | SurrealQL references non-existent page_numbers column. extraction.docling_complete never fires. |")
a("| 2 | MEDIUM | useV3SSE.ts:16-21 | TERMINAL_EVENT_TYPES missing extraction.complete and extraction.failed. Unnecessary reconnect loop. |")
a("| 3 | LOW | ExtractionLiveView.tsx:126 | Local TERMINAL_EVENT_TYPES also missing extraction.complete, extraction.failed, ai.save_complete. |")
a("| 4 | LOW | extract/page.tsx:86 | Same terminal event gap as ExtractionLiveView. |")
a()
a("### Recommendations")
a()
a("1. Fix Bug 1: Replace page_numbers query with page_start/page_end columns.")
a("2. Fix Bug 2: Add extraction.complete and extraction.failed to useV3SSE.ts TERMINAL_EVENT_TYPES.")
a("3. Fix Bugs 3-4: Update TERMINAL_EVENT_TYPES in ExtractionLiveView.tsx and extract/page.tsx.")
a("4. (Optional) Add dedicated rendering for new events in ExtractionLiveView.tsx.")
a("5. Start Langfuse before next E2E extraction run.")

out.write_text(chr(10).join(L), encoding="utf-8")
print("Written", len(L), "lines")
